### ISSUE TITLE
Python Implementation / Probable Bug 

### ISSUE THREAD

**Issue by ghost** [marianafranco/missionaries-and-cannibals#1]
There is a problem at line [149](https://github.com/marianafranco/missionaries-and-cannibals/blob/master/python/missionaries_and_cannibals.py#L149). This causes the program to run an infinite loop. The reason is each time a newstate is created, Python creates a new instance of that particular class which has a different memory address. By adding those to the `explored` and also checking for them in `frontier`, that line fails because objects with the same state has different memory address. I solved this problem by adding an additional instance method `reduce_state()` in order to store the state in `explored` set and also check against  `frontier`. If you can reproduce the problem or if i am making a mistake, please clarify.

Thanks

**Comment by marianafranco** [comment]
Hey @mitghi, would you mind to opening a PR with your fix? :smile:

**Comment by marianafranco** [comment]
Thanks @mitghi for your PR. I ended up fixing this problem by implementing the `__eq__` and `__hash__` methods in the `State` class (commit https://github.com/marianafranco/missionaries-and-cannibals/commit/6715576218ee216a72af7c4a4aa3b247fd9dcd7f).
